[package]
name = "neighbor_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0" }
dioxus-desktop = { version = "0.7.2" }
directories = "6.0.0"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"] # This feature is enabled during desktop builds
