[package]
name = "programming_4"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0" }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"] # This feature is enabled during desktop builds
