[build]
# note that this requires using nightly rustc
# which can be enabled for current directory with `rustc override set nightly`
# might require 
rustflags = [
    "-C", "link-arg=-fuse-ld=lld", 
    "-Z", "threads=8",
    "-A", "non_snake_case",
    "-Z", "macro-backtrace"]

# can be further optimized with:
#rustc-wrapper = "/path/to/sccache"
# this however should be placed in global config (~/.cargo/config.toml)
# to avoid committing it into VCS